### ISSUE TITLE
Multilingual: Disable the main feed and only provide language specific ones?

### ISSUE THREAD

**Issue by drallgood** [octopress/feeds#10]
Right now, this plugin creates a "main" feed (located at the root) for the primary language of the site.
Feeds for additional languages are created by adding a XML file to the language specific subfolder (e.g. de/feeds/index,xml).

So the feed urls would be:
- /feed/
- /de/feed/
- ...

To me, that sounds counter intuitive. 
I would expect:
- /en/feed/
- /de/feed/
- ...

And while you can still do that, the main feed at `/feed` is still generated.

What do you guys think?

**Comment by imathis** [comment]
I'm not sure what the best default case is. If people are already subscribed to a blog and they add this plugin, their feed location will change.

Right now you can configure the desired location for your feed by adding a config file at `_plugins/feeds/config.yml` and adding this:

``` yaml
page_permalinks:
  main-feed: en/feed/
  link-feed: en/feed/links/
  article-feed: en/feed/articles/
```

The docs for this [are here](https://github.com/octopress/ink/blob/master/assets/docs/working-with-plugins.markdown#changing-urls-for-plugin-pages) and of course once I'm done with the docs site, they'll be more visible.

This is one of those features that Octopress Ink plugins get for free, but trying to figure out how to communicate that to users is hard. I should probably include a note in the documentation of every plugin linking to the relevant doc in Octopress Ink.

**Comment by drallgood** [comment]
Yeah. I'm not sure about that either. If you're hosting it on your own server (like me) you can always redirect existing users, but that won't work in every case, e.g. when you're hosting it on Github.

Is there something I have to do besides adding the page_permalinks section?  It didn't do anything for me.

**Comment by imathis** [comment]
Sorry, I forgot I changed this and haven't updated the docs. Here's what you want in your config file:

``` yaml
permalinks:
  main-feed: /en/feed/
  link-feed: /en/feed/links/
  article-feed: /en/feed/articles/
```

I can make it automatically set these if the multilingual plugin is installed. I'm still thinking about it.

**Comment by imathis** [comment]
So I'm thinking about how I'd move the main feeds automatically, and it makes me wonder, would you also want your main index page to be at /en/index.html? Would you want all pages to be divided up by language? To me it seems like you'd have your main language be all standard URLs and then alternate languages would have their URLs prepended by the language. Changing the default location of the main feeds seems like it expects you to section off everything. I kind of doubt that's what most people will do. What do you think?

**Comment by imathis** [comment]
I've just released 1.2.4 which corrects a few minor things and updates the README to include information about setting permalinks for the feeds. You'll find it near the bottom in the Configuration section.

**Comment by drallgood** [comment]
> So I'm thinking about how I'd move the main feeds automatically, and it makes me wonder, would you also want your main index page to be at /en/index.html? Would you want all pages to be divided up by language?

That's how most pages do it. There are a few exceptions, though (e.g. apple.com). 
I don't think there is just one way of doing this. 

> Changing the default location of the main feeds seems like it expects you to section off everything.
> We're already going down that route with our posts. 

The good news is, that we don't have to choose. If you like to keep everything as-is and just add another language, just add the subfolders for that one language. If you want to have everything separate, just add another folder for your main language (that's what I did).

**Comment by drallgood** [comment]
As a side-note, pagination doesn't work when you have separate index.html files.
It expects the main index to be at the root of the page.

**Comment by drallgood** [comment]
And I think my site isn't even reading the config-file. The files still aren't being generated in the right place and I've enabled excerpts, but the feeds still contain the full posts.

**Comment by imathis** [comment]
Ok, so which scenarios aren't working for you?
- Excerpted feeds.
- Configurable permalinks

Anything else I need to fix?

**Comment by drallgood** [comment]
So far, that's about it :)

**Comment by imathis** [comment]
Cool, just to confirm, you've enabled excerpts in your `_plugins/feeds/config.yml` with:

``` yaml
excerpts: true
```

**Comment by drallgood** [comment]
yep.

Here's my config in it's entirety:

```
count: 20
excerpts: true         # Feed excerpts post content
external_links: true    # Linkposts should direct visitors to the linked site
permalinks:
  main-feed: /en/feed/
  link-feed: /en/feed/links/
  article-feed: /en/feed/articles/
```

**Comment by imathis** [comment]
Sweet. I'll add some new test cases.

**Comment by imathis** [comment]
Alright, I've released 1.2.5 with a bunch of added test cases. I've added tests cases and found the cause of several bugs. I expect that everything will be working properly now. Let me know if that's not the case.

**Comment by drallgood** [comment]
hmm... Didn't change anything for me.

**Comment by imathis** [comment]
I'm not sure how that's possible. In a typical Jekyll site, you'll configure your Octopress Ink plugins at `_plugins/feeds/config.yml`. If you have some other kind of setup, for example, if your source is in a directory, `source` then your plugins folder will typically be in `source/_plugins`. If you have some other configuration, be sure that the configuration is in `[wherever_your_plugins_directory_is]/feeds/config.yml`

If all that is set up and this is still not working, perhaps you can help me create a test case that I'm somehow missing.

**Comment by drallgood** [comment]
My site is based on the old Octopress 2 layout, so it basically looks like this:

```
- /source
- /plugins
- /_config.yml
```

Following the documentation, I let ink create the config file for me: `bundle exec octopress ink copy feeds --config-file` 
It copied it to `plugins/feeds/config.yml`

I'm going to create a new site, to see whether this issue is related to my particular setup.

**Comment by imathis** [comment]
I've set up test cases for just about everything I can think of and I can't get it to break. I hope you're able to find something. Thanks again for your persistence. You're efforts have really helped me make this better.

**Comment by imathis** [comment]
I've decided to go ahead and change the defaults to namespacing all feeds by language if octopress-multilingual is installed.

**Comment by drallgood** [comment]
I've confirmed, that this only happens if the project has a separate source folder.
It doesn't read the config if I move my plugins into `source/_plugins` or even just rename it to `_plugins`.

**Comment by imathis** [comment]
@drallgood Thanks for sorting this out. I'll add a test case to Octopress Ink and see if I can get this fixed.

**Comment by imathis** [comment]
I know you're probably tired of hearing me say "I fixed it", but… "I fixed it!" Update to the latest Octopress Ink and you should be good. Thanks a bunch for helping me find this one!

**Comment by drallgood** [comment]
Awesome. I think that did it!
Thanks!!!

I'm getting another exception in Ink (probably due to something you changed today/yesterday), but I'm going to open up an issue there :)

I'm guessing, this task can be closed now?

**Comment by imathis** [comment]
Yep, I closed it when I changed the default permalink scheme for multilingual sites.
