### ISSUE TITLE
octopress ink copy feeds invalid path

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/feeds#12]
Running `octopress ink copy feeds` from the Jekyll root will copy the feeds into the incorrect directory. For example:

In `/a/b/c/jekyll-root/` if I run `octopress ink copy feeds`, the config files will be copied to 

```
/a/b/c/jekyll-root/a/b/c/jekyll-root/_plugins/...
```

instead of 

```
/a/b/c/jekyll-root/_plugins/...
```

**Comment by imathis** [comment]
I just released a new version of Octopress Ink. If you would, `bundle update` and let me know if that fixes it.

**Comment by chauncey-garrett** [comment]
works :+1:

**Comment by imathis** [comment]
Excellent!
