### ISSUE TITLE
{% feeds %} tag should use double quotes in link tag

### ISSUE THREAD

**Issue by maiertech** [octopress/feeds#16]
The generated link tag uses single quotes

```
<link href='/ddddd/feed/' title='Posts - Bla Bla' rel='alternate' type='application/atom+xml'>
```

and Atom throws a warning for the generated page saying double quotes should be used. Same for the CSS and JS tags.

**Comment by imathis** [comment]
I've fixed this. I'll bundle this with a release that fixes https://github.com/octopress/asset-pipeline/issues/11 tonight hopefully.
