### ISSUE TITLE
uninitialized constant Octopress::Ink

### ISSUE THREAD

**Issue by drallgood** [octopress/feeds#18]
I'm getting this since the last update:

> /Library/Ruby/Gems/2.0.0/gems/octopress-feeds-2.0.4/lib/octopress-feeds.rb:8:in `<top (required)>': uninitialized constant Octopress::Ink (NameError)

**Comment by imathis** [comment]
What command are you running to get this? Does `bundle exec [whatever command]` make a difference?

**Comment by drallgood** [comment]
That's what I'm doing:
`bundle exec jekyll serve -t`

And here's my Gemfile:

```
source 'https://rubygems.org'

gem "octopress", "~> 3.0.0.rc.10"

#JS runtime for build
gem 'execjs'
gem 'typhoeus'
gem 'therubyracer'

group :jekyll_plugins do
  gem 'octopress-genesis-theme'
  gem 'octopress-feeds'
  gem 'octopress-asset-pipeline'
  gem 'octopress-paginate'
end
```

**Comment by imathis** [comment]
I think you may want to change your octopress gem to `gem "octopress", "~> 3.0"`, update, and try again. Let me know if that fixes it for you.

**Comment by drallgood** [comment]
I did not :disappointed:

**Comment by imathis** [comment]
Thanks so much for posting this. I figured it out! I poked around in the Bundler code and figured out it was some issue with the way I was loading Gemfile groups. Anyhow, update to Octopress 3.0.6 and you should be good to go.

**Comment by drallgood** [comment]
Yep. That did it!

Thanks!

**Comment by imathis** [comment]
Excellent. Thanks again!
