### ISSUE TITLE
Error on Jekyll build.

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/feeds#2]
On `jekyll build`, I receive the following error:

```
Configuration file: /Users/username/site.io/_config.yml
            Source: /Users/username/site.io
       Destination: public
      Generating...
  Liquid Exception: Unknown tag 'abort' in article-feed.xml
jekyll 2.4.0 | Error:  Unknown tag 'abort'
```

I've checked the Gemfile and `octopress-abort-tag` is included.

`octopress ink list feeds` will give:

```
octopress 3.0.0.rc.16 | Error:  undefined method `each' for nil:NilClass
```

but my understanding is that that command is reserved for after a successful build.

**Comment by imathis** [comment]
Hmm, I'll take a look at it. Thanks for the report.

**Comment by imathis** [comment]
I've just released the fix in version 1.1.0. Thanks again!

**Comment by chauncey-garrett** [comment]
`octopress ink list feeds` works now for me. Glad to help out. You guys are doing a great job!

**Comment by imathis** [comment]
Woohoo! Thanks :)
