### ISSUE TITLE
NilClass with Time failed in article-feed.xml

### ISSUE THREAD

**Issue by justinrummel** [octopress/feeds#4]
Following the directions from my [previous issue](https://github.com/octopress/ink/issues/31) and doing a `bundle update` then a `jekyll b`, I'm receiving this error when trying to enable feeds: 

``` bash
Generating... 
Liquid Exception: comparison of NilClass with Time failed in article-feed.xml
jekyll 2.5.3 | Error:  comparison of NilClass with Time failed
```

**Comment by imathis** [comment]
Is your site source hosted publicly? If so if you could provide me a link, or a bit more information about which plugins you're using and how you're set up that would be awesome. I'm going to try to recreate this issue and create a test for it.

**Comment by justinrummel** [comment]
Just created a repo at: https://github.com/justinrummel/jr.com-octo3 

Outside of the default `octopuses new www` that I used to initialize the site, I added my Octopress 2 _posts which did require a couple of plugins to be migrated from the Octopress 2 repository that are visible in: https://github.com/justinrummel/jr.com-octo3/tree/master/www/_plugins

**Comment by imathis** [comment]
Thanks!

**Comment by imathis** [comment]
That was really helpful. I believe I've fixed your issue. I've released version 1.1.1. Give it a try and let me know.

**Comment by imathis** [comment]
As fate would have it, there was a bug in 1.1.1 so… 1.1.2 is out!

**Comment by justinrummel** [comment]
Perfect!  It's now building without errors!

**Comment by imathis** [comment]
Sweet deal. Also you should be able to replace your block quote plugin with octopress-quote-tag. I tried it out and everything built fine. You may have to do some styles for it though.
