### ISSUE TITLE
Invalid feed build for articles-only and link post types

### ISSUE THREAD

**Issue by chauncey-garrett** [octopress/feeds#6]
Having checked both the ruby code and the assets folders, I'm not quite sure where this is coming from but the abridged feeds have a new line at the beginning of the xml file that invalidates the feed (at least in Firefox while using Pow). Manual removal of this line from the generated abridged feed allows the feed to correctly show. The unabridged feed does not have this new line.

Broken:

```

<?xml version="1.0" encoding="utf-8"?>
...
```

Manually fixed:

```
<?xml version="1.0" encoding="utf-8"?>
...
```

**Comment by imathis** [comment]
Thanks, I'm working an a new build that fixes this.

**Comment by imathis** [comment]
I've just released 1.1.4 which should fix this. `bundle update` and let me know :)

**Comment by chauncey-garrett** [comment]
Ahh that's why I couldn't find the bug. I didn't realize liquid would leave a blank line if the if statement didn't pass. Good to know!

I'll bundle update after dinner and confirm that it works.

**Comment by chauncey-garrett** [comment]
**which I believe that it should.

**Comment by chauncey-garrett** [comment]
Works!

**Comment by imathis** [comment]
Rockin'!
